version: '3.8'

services:
  inventory-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventorydb


  order-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderdb


  inventory-service:
    build: ./inventory-service
    ports:
      - "50051:50051"
    environment:
      - DB_URL=postgres://postgres:postgres@inventory-db:5432/inventorydb?sslmode=disable
    depends_on:
      - inventory-db

  order-service:
    build: ./order-service
    ports:
      - "50052:50052"
    environment:
      - DB_URL=postgres://postgres:postgres@order-db:5432/orderdb?sslmode=disable
    depends_on:
      - order-db

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - inventory-service
      - order-service