  order-service:
    build: ./order-service
    ports:
      - "50052:50052"
    environment:
      - DB_URL=postgres://postgres:postgres@order-db:5432/orderdb?sslmode=disable
    depends_on:
      - order-db

  order-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderdb
    volumes:
      - ./order-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"