  inventory-service:
    build: ./inventory-service
    ports:
      - "50051:50051"
    environment:
      - DB_URL=postgres://postgres:postgres@inventory-db:5432/inventorydb?sslmode=disable
    depends_on:
      - inventory-db

  inventory-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventorydb
    ports:
      - "5433:5432"